### ISSUE TITLE
Implement Balanced Neural Ratio Estimation loss

### ISSUE THREAD

**Issue by ADelau** [francois-rozet/lampe#2]
### Description

Implementation of Balanced Neural Ratio Estimation  (BNRE) as introduced in "Towards Reliable Simulation-Based Inference with Balanced Neural Ratio Estimation" (Delaunoy et al., 2022)

### Implementation

An implementation of the BNRE loss similar to the NRELoss

### Alternatives

None

**Comment by francois-rozet** [comment]
Your PR (#3) has been merged. Thank you!
