### ISSUE TITLE
Improve the `build` docstrings

### ISSUE THREAD

**Issue by glouppe** [francois-rozet/lampe#9]
The documentation of the `build` constructor argument in NRE/NPE/NSE specifies

```
build: Callable[[int, int], nn.Module] = MLP
```
and 
```
build: The network constructor
```

In my opinion, this does not really help in understanding how this constructor argument should be used, as there is no mention of what the ints are referring to. It is also not clear what the `nn.Module` should expect as inputs and produce as outputs. 

In the tutorial about embeddings, it could also be helpful to explain how the network produced with `build` is different from the network used to build an embedding.

**Comment by francois-rozet** [comment]
Would the following be enough?

```
build: The network constructor (e.g. :class:`lampe.nn.ResMLP`). It takes the
    number of input and output features as positional arguments.
```

For the embedding tutorial, the following paragraph explains why we need an embedding. Should we add something?

> Because the observations are images, they cannot be fed directly to a `NPE` module, which only accepts vector-shaped observations. Instead, we rely on a convolutional neural network to extract a vector of informative features from the observation and feed this vector to the density estimator. In our case, the latter is a [neural spline flow](https://arxiv.org/abs/1906.04032) (NSF) with rational-quadratic splines borrowed from the [`zuko`](zuko) package.

**Comment by francois-rozet** [comment]
The constructor descriptions have been updated in 83fd155c6a3cb77fe55648de2273fdd093ea0b6c.
